server:
  port: 8080
  tomcat:
    max-http-form-post-size: 1000MB

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${ datasource_url }
    username: ${ datasource_username }
    password: ${ datasource_password }

  springdoc:
    packages-to-scan: com.sherpa.exambank
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
    swagger-ui:
      path: /swagger-ui
      disable-swagger-default-url: true
      display-request-duration: true
      operations-sorter: alpha

  # jsp setting
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # live reload setting - auto reload
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 10MB
      max-request-size: 10MB
      location: ${ servlet_multipart_location }

mybatis:
  mapper-locations: mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    callSettersOnNulls: true

logging:
  level:
    org.springframwork.web : debug
    sql : off
    jdbc : off
    jdbc.sqlonly : debug
